# Copyright (c) 2020-present, The kubequery authors
#
# This source code is licensed as defined by the LICENSE file found in the
# root directory of this source tree.
#
# SPDX-License-Identifier: (Apache-2.0 OR GPL-2.0-only)

name: Build

on:
  push:
    branches: [ master ]
    tags: [ "**" ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Detect tag
      id: vars
      run: |
        if [[ "$GITHUB_REF" == "refs/heads/master" ]]; then
          echo ::set-output name=tag::latest
        elif [[ $GITHUB_REF = refs/tags/* ]]; then
          echo ::set-output name=tag::$(echo $GITHUB_REF | cut -d / -f 3)
        else
          echo ::set-output name=tag::
        fi

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        echo "Image tag: ${{ steps.vars.outputs.tag }}"
        VERSION=${{ steps.vars.outputs.tag }} make

    - name: DockerHub login
      uses: docker/login-action@v1
      if: steps.vars.outputs.tag != ''
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push image
      if: steps.vars.outputs.tag != ''
      run: |
        docker build --build-arg KUBEQUERY_VERSION=${{ steps.vars.outputs.tag }} --tag uptycs/kubequery:${{ steps.vars.outputs.tag }} .
        docker push uptycs/kubequery:${{ steps.vars.outputs.tag }}

    - name: Configure Git
      if: steps.vars.outputs.tag != ''
      run: |
        git config user.name "uptycsdog"
        git config user.email "bot@uptycs.com"

    - name: Run chart-releaser
      if: steps.vars.outputs.tag != ''
      uses: helm/chart-releaser-action@v1.2.1
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
